### ISSUE TITLE
Device address wrong?

### ISSUE THREAD

**Issue by ChrisMurphyBM** [jposada202020/MicroPython_MMA8452Q#1]
on line 118 i had to change my device address from 0x1C to 0x1d to get it to work
 
 "def __init__(self, i2c, address: int = 0x1C) -> None:"
"def __init__(self, i2c, address: int = 0x1d) -> None:"

**Comment by jposada202020** [comment]
Hello depending on the Sensor Brand that you have, you will have 0x1C or 0x1D. for reference https://learn.sparkfun.com/tutorials/qwiic-accelerometer-mma8452q-hookup-guide/all
